FROM golang:latest

LABEL maintainer="Jians <294041820@qq.com>"

WORKDIR $GOPATH/src

#RUN go env -w GO111MODULE=on
#RUN go env -w GOPROXY=https://mirrors.aliyun.com/goproxy/,direct

#RUN go get -u github.com/cosmtrek/air

#CMD [ "air" ]
